# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [60]:
sns.set(style="whitegrid")

#Load the dataset
df = pd.read_csv('data/AviationData.csv', encoding='latin1', low_memory=False)

# Preview
df.head(50)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
5,20170710X52551,Accident,NYC79AA106,1979-09-17,"BOSTON, MA",United States,42.445277,-70.758333,NaN,NaN,...,NaN,Air Canada,NaN,NaN,1.0,44.0,VMC,Climb,Probable Cause,19-09-2017
6,20001218X45446,Accident,CHI81LA106,1981-08-01,"COTTON, MN",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,IMC,Unknown,Probable Cause,06-11-2001
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,HANOVER,...,Business,NaN,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982
9,20020909X01560,Accident,MIA82DA029,1982-01-01,"JACKSONVILLE, FL",United States,NaN,NaN,JAX,JACKSONVILLE INTL,...,Personal,NaN,0.0,0.0,3.0,0.0,IMC,Cruise,Probable Cause,01-01-1982
10,20020909X01559,Accident,FTW82DA034,1982-01-01,"HOBBS, NM",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,Approach,Probable Cause,01-01-1982
11,20020909X01558,Accident,ATL82DKJ10,1982-01-01,"TUSKEGEE, AL",United States,NaN,NaN,NaN,TUSKEGEE,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,Landing,Probable Cause,01-01-1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,HEARNE MUNICIPAL,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983
14,20020917X02119,Accident,FTW82FPJ10,1982-01-02,"CHICKASHA, OK",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
15,20020917X02117,Accident,FTW82FPG08,1982-01-02,"LITTLE ROCK, AR",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
16,20020917X01962,Accident,DEN82DTM08,1982-01-02,"MIDWAY, UT",United States,NaN,NaN,NaN,FIELD RANCH,...,Personal,NaN,0.0,0.0,0.0,1.0,IMC,Taxi,Probable Cause,02-01-1983
17,20020917X01656,Accident,ANC82FAG14,1982-01-02,"SKWENTA, AK",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,3.0,0.0,0.0,0.0,VMC,Unknown,Probable Cause,02-01-1983
18,20020917X02481,Accident,NYC82DA016,1982-01-02,"GALETON, PA",United States,NaN,NaN,5G6,CHERRY SPRINGS,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,Taxi,Probable Cause,02-01-1983
19,20020917X02339,Accident,MIA82DA028,1982-01-02,"MIAMI, FL",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Cruise,Probable Cause,02-01-1983
20,20020917X01894,Accident,CHI82FEC08,1982-01-02,"YPSILANTI, MI",United States,NaN,NaN,YIP,WILLOW RUN,...,Instructional,NaN,0.0,0.0,0.0,1.0,VMC,Takeoff,Probable Cause,02-01-1983
21,20020917X01776,Accident,CHI82DA020,1982-01-02,"CHARLOTTE, MI",United States,NaN,NaN,49G,TINKERBELL,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Approach,Probable Cause,02-01-1983
22,20020917X01657,Accident,ATL82DA027,1982-01-02,"CHAMBLEE, GA",United States,NaN,NaN,PDK,NaN,...,Unknown,"Rocky Mountain Helicopters, In",0.0,0.0,0.0,1.0,VMC,Approach,Probable Cause,02-01-1983
23,20020917X02333,Incident,LAX82IA034,1982-01-03,"VAN NUYS, CA",United States,NaN,NaN,VNY,VAN NUYS,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,Approach,Probable Cause,03-01-1983
24,20020917X02255,Accident,LAX82FA040,1982-01-03,"10 NM W LEE VIN, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,1.0,0.0,0.0,IMC,Descent,Probable Cause,03-01-1983
25,20020917X01905,Accident,DCA82AA008,1982-01-03,"ASHLAND, VA",United States,NaN,NaN,NaN,HANOVER COUNTY,...,Business,NaN,8.0,0.0,0.0,0.0,IMC,Approach,Probable Cause,03-01-1983
26,20020917X01720,Accident,ATL82FA033,1982-01-03,"PINEHURST, NC",United States,NaN,NaN,SOP,MOORE COUNTY,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Approach,Probable Cause,03-01-1983
27,20020917X02483,Accident,NYC82DA018,1982-01-03,"WHITE PLAINS, NY",United States,NaN,NaN,HPN,WESTCHESTER COUNTY,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Landing,Probable Cause,03-01-1983
28,20020917X02340,Accident,MIA82DA030,1982-01-03,"COCOA, FL",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,1.0,1.0,VMC,Descent,Probable Cause,03-01-1983
29,20020917X02155,Accident,LAX82DA035,1982-01-03,"SAN CLEMENTINE, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,2.0,0.0,VMC,Maneuvering,Probable Cause,03-01-1983
30,20020917X01992,Accident,FTW82DA036,1982-01-03,"FORT WORTH, TX",United States,NaN,NaN,NaN,OAK GROVE,...,Personal,NaN,0.0,0.0,2.0,0.0,VMC,Approach,Probable Cause,03-01-1983
31,20020917X01960,Accident,DEN82DTI09,1982-01-03,"GREENOUGH, MT",United States,NaN,NaN,NaN,NaN,...,Ferry,NaN,0.0,0.0,0.0,1.0,VMC,Takeoff,Probable Cause,03-01-1983
32,20020917X02618,Accident,SEA82FA015,1982-01-04,"PLEASANT HILL, OR",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,VMC,Cruise,Probable Cause,04-01-1983
33,20020917X02254,Accident,LAX82FA038,1982-01-04,"NEAR LAS VEGAS, NV",United States,NaN,NaN,NaN,NaN,...,Unknown,Lang Air Service,2.0,0.0,0.0,0.0,VMC,Cruise,Probable Cause,04-01-1983
34,20020917X01880,Accident,CHI82FA019,1982-01-04,"FORT WAYNE, IN",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,2.0,0.0,0.0,IMC,Cruise,Probable Cause,04-01-1983
35,20020917X01991,Accident,FTW82DA035,1982-01-04,"ESTANCIA, NM",United States,NaN,NaN,E92,ESTANCIA MUNICIPAL,...,Personal,NaN,0.0,0.0,2.0,0.0,VMC,Cruise,Probable Cause,04-01-1983
36,20020917X02410,Accident,MIA82FKA05,1982-01-04,SAINT CROIX,NaN,NaN,NaN,STX,ALEXANDER HAMILTON,...,Business,NaN,1.0,0.0,1.0,0.0,VMC,Taxi,Probable Cause,04-01-1983
37,20020917X02304,Accident,LAX82FUM06,1982-01-05,"RAMONA, CA",United States,NaN,NaN,L39,RAMONA,...,Business,NaN,3.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,05-01-1983
38,20020917X02253,Accident,LAX82FA036,1982-01-05,"BLACK CANYON CI, AZ",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,05-01-1983
39,20020917X01906,Accident,DCA82AA009,1982-01-05,"ITHACA, NY",United States,NaN,NaN,NaN,TOMPKINS COUNTY,...,Unknown,Empire Airlines,2.0,0.0,0.0,0.0,VMC,Approach,Probable Cause,05-01-1983
40,20020917X01764,Incident,ATL82IA029,1982-01-05,"PENSACOLA, FL",United States,NaN,NaN,NaN,NaN,...,Business,NaN,0.0,0.0,0.0,1.0,VMC,Cruise,Probable Cause,05-01-1983
41,20020917X01993,Accident,FTW82DA037,1982-01-05,"LONOKE, AR",United States,NaN,NaN,NaN,NaN,...,Business,NaN,0.0,1.0,0.0,1.0,VMC,Descent,Probable Cause,05-01-1983
42,20020917X01658,Accident,ATL82DA028,1982-01-05,"GASTONIA, NC",United States,NaN,NaN,0A6,NaN,...,Ferry,NaN,0.0,0.0,0.0,1.0,VMC,Cruise,Probable Cause,05-01-1983
43,20020917X02156,Accident,LAX82DA037,1982-01-05,"SPRINGERVILLE, AZ",United States,NaN,NaN,Q35,SPRINGERVILLE,...,Unknown,Joel Frederick's Monarch Air,0.0,0.0,0.0,1.0,VMC,Taxi,Probable Cause,05-01-1983
44,20020917X01651,Accident,ANC82FA012,1982-01-05,"BETHEL, AK",United States,NaN,NaN,BET,BETHEL,...,Unknown,Executive Charter Service,0.0,2.0,0.0,0.0,VMC,Takeoff,Probable Cause,05-01-1983
45,20020917X02423,Accident,MKC82DA016,1982-01-06,"ROLLA, MO",United States,NaN,NaN,K07,DOWNTOWN,...,Executive/corporate,NaN,0.0,0.0,0.0,3.0,VMC,Approach,Probable Cause,06-01-1983
46,20020917X02157,Accident,LAX82DA039,1982-01-06,"MAMMOTH LAKES, CA",United States,NaN,NaN,MMH,MAMMOTH LAKES,...,Business,NaN,0.0,0.0,0.0,6.0,VMC,Taxi,Probable Cause,06-01-1983
47,20020917X01913,Accident,DEN82DA015,1982-01-06,"JACKSON, WY",United States,NaN,NaN,NaN,JACKSON HOLE,...,Personal,NaN,0.0,0.0,0.0,3.0,VMC,Climb,Probable Cause,06-01-1983
48,20020917X01777,Accident,CHI82DA021,1982-01-06,"PAXTON, IL",United States,NaN,NaN,1C1,PAXTON MUNICIPAL,...,Instructional,NaN,0.0,0.0,0.0,2.0,VMC,Approach,Probable Cause,06-01-1983
49,20020917X01757,Accident,ATL82FLG08,1982-01-06,"HILTON HEAD, SC",United States,NaN,NaN,NaN,NaN,...,Business,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,06-01-1983

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [61]:
# Standardize column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('.', '', regex=False)
# Clean the aircraftdamage column
df['aircraftdamage'] = df['aircraftdamage'].str.upper().str.strip()

# Convert event_date to datetime and filter for aircraft that could still be in use (1983+)
df.rename(columns={'eventdate': 'event_date'}, inplace=True)
df['event_date'] = pd.to_datetime(df['event_date'], errors='coerce')
df = df[df['event_date'].dt.year >= 1983]

# Remove non-professional aircraft (experimental, homebuilt, ultralight, unknown)
df = df[~df['make'].str.contains('EXPERIMENTAL|HOMEBUILT|ULTRALIGHT|UNKNOWN', na=False, case=False)]

# Keep only rows with known aircraft damage AND at least one fatal or serious injury value present
df = df[df['aircraftdamage'].notna()]
df = df[(df['totalfatalinjuries'].notna()) | (df['totalseriousinjuries'].notna())]

# Create a flag for whether the purpose of flight is known (not used for filtering yet)
df['known_purpose'] = df['purposeofflight'].notna().astype(int)

# Preview result
len(df)

72512

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [62]:
# Define and fill injury-related columns
injury_cols = [
    'totalfatalinjuries',
    'totalseriousinjuries',
    'totalminorinjuries',
    'totaluninjured'
]

df[injury_cols] = df[injury_cols].fillna(0)

# Estimate total occupants
df['total_occupants'] = (
    df['totalfatalinjuries'] +
    df['totalseriousinjuries'] +
    df['totalminorinjuries'] +
    df['totaluninjured']
)

# Calculate injury rate
df['serious_or_fatal_injury_rate'] = (
    (df['totalfatalinjuries'] + df['totalseriousinjuries']) / df['total_occupants']
)

# Create binary flag
df['any_serious_or_fatal_injury'] = df['serious_or_fatal_injury_rate'].apply(lambda x: 1 if x > 0 else 0)

# Preview 
df[injury_cols + ['total_occupants', 'serious_or_fatal_injury_rate', 'any_serious_or_fatal_injury']].head(10)

,totalfatalinjuries,totalseriousinjuries,totalminorinjuries,totaluninjured,total_occupants,serious_or_fatal_injury_rate,any_serious_or_fatal_injury
3601,0.0,0.0,1.0,3.0,4.0,0.0,0
3602,0.0,0.0,0.0,2.0,2.0,0.0,0
3603,0.0,0.0,0.0,1.0,1.0,0.0,0
3604,0.0,0.0,2.0,0.0,2.0,0.0,0
3605,0.0,0.0,0.0,2.0,2.0,0.0,0
3607,0.0,0.0,4.0,0.0,4.0,0.0,0
3608,2.0,0.0,0.0,0.0,2.0,1.0,1
3609,3.0,0.0,0.0,0.0,3.0,1.0,1
3610,0.0,0.0,0.0,2.0,2.0,0.0,0
3611,0.0,0.0,0.0,3.0,3.0,0.0,0

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [63]:
df['aircraftdamage'] = df['aircraftdamage'].str.upper().str.strip()
df['destroyed'] = df['aircraftdamage'].apply(lambda x: 1 if x == 'DESTROYED' else 0)

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

In [64]:
# Clean the make column  
df['make'] = df['make'].str.upper().str.strip()

# Consolidation
df['make'] = df['make'].replace({
    'ROBINSON HELICOPTER': 'ROBINSON',
    'ROBINSON HELICOPTER COMPANY': 'ROBINSON',
    'AIR TRACTOR INC': 'AIR TRACTOR',
    'GRUMMAN AMERICAN': 'GRUMMAN',
    'CIRRUS DESIGN CORP': 'CIRRUS'
})
# Check value counts
make_counts = df['make'].value_counts()
make_counts.head(50)

# aircraft identifier
df['make_model'] = df['make'] + ' ' + df['model']

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [65]:
# Missing model values 
df = df[df['model'].notna()]

# Standardize
df['model'] = df['model'].str.upper().str.strip()

#Check for overlap
make_model_counts = df.groupby(['make', 'model']).size().reset_index(name='count')
model_duplicates = make_model_counts['model'].value_counts()
model_duplicates[model_duplicates > 1].head(10)

df[['make', 'model', 'make_model']].head(10)

                make       model           make_model
3601          CESSNA        182P          CESSNA 182P
3602          CESSNA       182RG         CESSNA 182RG
3603          CESSNA        182P          CESSNA 182P
3604           PIPER  PA-28R-200     PIPER PA-28R-200
3605          CESSNA         140           CESSNA 140
3607          CESSNA        340A          CESSNA 340A
3608  NORTH AMERICAN        T-6G  NORTH AMERICAN T-6G
3609           PIPER   PA-24-250      PIPER PA-24-250
3610           PIPER  PA-32-301R     PIPER PA-32-301R
3611           BEECH       V-35B          BEECH V-35B

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [66]:
# Clean engine type
df['enginetype'] = df['enginetype'].str.upper().str.strip()

# Clean weather condition
df['weathercondition'] = df['weathercondition'].str.upper().str.strip()

# Convert number of engines to numeric (in case some are still strings)
df['numberofengines'] = pd.to_numeric(df['numberofengines'], errors='coerce')

# Clean purpose of flight
df['purposeofflight'] = df['purposeofflight'].str.upper().str.strip()

# Clean broad phase of flight
df['broadphaseofflight'] = df['broadphaseofflight'].str.upper().str.strip()

# Preview

df['enginetype'].value_counts(dropna=False)
df['weathercondition'].value_counts(dropna=False)
df['numberofengines'].value_counts(dropna=False)
df['purposeofflight'].value_counts(dropna=False)
df['broadphaseofflight'].value_counts(dropna=False)

broadphaseofflight
NaN            24839
LANDING        10891
TAKEOFF         9860
CRUISE          8126
MANEUVERING     6930
APPROACH        5248
CLIMB           1636
DESCENT         1408
TAXI            1327
GO-AROUND       1098
STANDING         546
UNKNOWN          468
OTHER             88
Name: count, dtype: int64

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [67]:
# Get count and % of missing values per column
null_summary = df.isnull().sum().to_frame(name='missing_count')
null_summary['missing_percent'] = (null_summary['missing_count'] / len(df)) * 100
null_summary = null_summary.sort_values(by='missing_percent', ascending=False)

# Drop columns with more than 50% missing values
cols_to_drop = null_summary[null_summary['missing_percent'] > 50].index
df.drop(columns=cols_to_drop, inplace=True)
df.drop(columns=['airportcode', 'airportname'], inplace=True)
# Preview
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 72465 entries, 3601 to 88886
Data columns (total 29 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   eventid                       72465 non-null  object
 1   investigationtype             72465 non-null  object
 2   accidentnumber                72465 non-null  object
 3   event_date                    72465 non-null  datetime64[ns]
 4   location                      72427 non-null  object
 5   country                       72270 non-null  object
 6   injuryseverity                71980 non-null  object
 7   aircraftdamage                72465 non-null  object
 8   registrationnumber            71643 non-null  object
 9   make                          72454 non-null  object
 10  model                         72465 non-null  object
 11  amateurbuilt                  72430 non-null  object
 12  numberofengines               68102 non-null  float64
 13  enginetype                    67181 non-null  object
 14  purposeofflight               68798 non-null  object
 15  totalfatalinjuries            72465 non-null  float64
 16  totalseriousinjuries          72465 non-null  float64
 17  totalminorinjuries            72465 non-null  float64
 18  totaluninjured                72465 non-null  float64
 19  weathercondition              69346 non-null  object
 20  broadphaseofflight            47626 non-null  object
 21  reportstatus                  67165 non-null  object
 22  publicationdate               59422 non-null  object
 23  known_purpose                 72465 non-null  int64
 24  total_occupants               72465 non-null  float64
 25  serious_or_fatal_injury_rate  71924 non-null  float64
 26  any_serious_or_fatal_injury   72465 non-null  int64
 27  destroyed                     72465 non-null  int64
 28  make_model                    72454 non-null  object
dtypes: datetime64[ns](1), float64(7), int64(3), object(18)
memory usage: 16.6+ MB

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [68]:
# Generate a summary of the cleaned dataset
summary = {
    "Total rows": len(df),
    "Total columns": df.shape[1],
    "Columns with missing values": df.isnull().sum()[df.isnull().sum() > 0].to_dict(),
    "Dropped columns": ['airportcode', 'airportname'],
    "Target variables": ['destroyed', 'serious_or_fatal_injury_rate'],
    "Identifier used": 'make_model'
}

# Print summary to notebook
for key, value in summary.items():
    print(f"{key}: {value}")

# Save to CSV
df.to_csv('cleaned_aviation_data.csv', index=False)

Total rows: 72465
Total columns: 29
Columns with missing values: {'location': 38, 'country': 195, 'injuryseverity': 485, 'registrationnumber': 822, 'make': 11, 'amateurbuilt': 35, 'numberofengines': 4363, 'enginetype': 5284, 'purposeofflight': 3667, 'weathercondition': 3119, 'broadphaseofflight': 24839, 'reportstatus': 5300, 'publicationdate': 13043, 'serious_or_fatal_injury_rate': 541, 'make_model': 11}
Dropped columns: ['airportcode', 'airportname']
Target variables: ['destroyed', 'serious_or_fatal_injury_rate']
Identifier used: make_model

In [69]:
df.to_csv('cleaned_aviation_data.csv', index=False)